name: Upload Website

on:
  push:
    branches:
    - update-wf-step
env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
permissions:
  id-token: write
jobs:
  deploy-to-s3:
    name: Deploy to S3
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-west-1
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: DeployWebsite
        unset-current-credentials: true
        output-credentials: true
        role-duration-seconds: 900
    
    - uses: actions/checkout@master
    - name: Sync Website files to S3
      run: aws s3 sync ./WebFiles s3://${{ secrets.AWS_S3_BUCKET }} --acl public-read --follow-symlinks --delete --exclude '.github/*' --exclude '.git/*' --exclude '*.gitignore' --exclude '.DS_Store' --region us-west-1
    
    - uses: skolobov/gh-action-slack@v1
      with: 
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
      if: always()
  # Invalidate files on cloudfront
  cdf-invalidation:
      name: Invalidate CloudFront
      runs-on: ubuntu-latest
      needs:
        - deploy-to-s3
      steps:
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          AWS_REGION: us-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: "/*"

      - uses: skolobov/gh-action-slack@v1
        with: 
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
